FROM centos:7.9.2009 as build

WORKDIR /tmp
RUN curl -o rust.sh https://sh.rustup.rs -sSf \
 && chmod a+x rust.sh \
 && ./rust.sh -y -q --profile minimal \
 && rm rust.sh

RUN ln -s /root/.cargo/bin/* /usr/local/bin

RUN yum install -y openssl-devel \
 && yum groupinstall -y "Development Tools"

WORKDIR /unstuck/src
COPY . .

RUN cargo build --release

FROM centos:7.9.2009

COPY --from=build /unstuck/src/target/release/unstuck /usr/local/bin

ENTRYPOINT ["unstuck"]
